In [7]:
import numpy as np

#### le type avec numpy

In [12]:

num = np.array([3,4.0,6])
print(num.dtype)

float64


In [15]:
t = np.array([[1,2],[3,4]])
print(t)

[[1 2]
 [3 4]]


## exemple tableau matrice


In [21]:
tb = np.array([[1,4],[3,4],[3,5],[5,2]])
print(tb)

[[1 4]
 [3 4]
 [3 5]
 [5 2]]


## les tableaux multidimensionnels numpy


In [28]:
##la fonction zeros,ones permetent d'initialiser le tableau rempli avec des zeros 
##specifier le nonbre de lihne et le nombre de colonne
t0 = np.zeros((5,6), dtype =np.int32)### dtype =np.int32 pour changer le type en entier
t0

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [29]:
t1 = np.ones(3)
t1

array([1., 1., 1.])

In [31]:
t1 = np.ones(3)
t11 = np.ones((4,6))
t11

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## full permet de remplir le tableau en choisissant une valeur donné

In [35]:
t2 = np.full((5,7),9)
t2

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

## le tableau des nombres aleatoires

In [37]:
t_r = np.random.randn(4,5)
t_r

array([[ 0.65114488,  0.59806758,  1.56710527, -1.50902954,  0.26080415],
       [ 0.41774434,  1.26010972,  2.52127352,  0.78172221, -0.30914492],
       [-2.05004597, -2.67691682,  0.64825741,  0.16621417, -0.44996156],
       [ 0.75883942, -0.87666716,  0.45731358,  1.6531109 ,  0.7623057 ]])

In [39]:
#####tableau matrice identité
t_mi = np.eye(8)
t_mi

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [42]:
#### creation de tableau espacer
t_e = np.arange(1,7)
t_e

array([1, 2, 3, 4, 5, 6])

In [48]:
###tableau linéaire
t_l = np.linspace(0,30)
t_l

array([ 0.        ,  0.6122449 ,  1.2244898 ,  1.83673469,  2.44897959,
        3.06122449,  3.67346939,  4.28571429,  4.89795918,  5.51020408,
        6.12244898,  6.73469388,  7.34693878,  7.95918367,  8.57142857,
        9.18367347,  9.79591837, 10.40816327, 11.02040816, 11.63265306,
       12.24489796, 12.85714286, 13.46938776, 14.08163265, 14.69387755,
       15.30612245, 15.91836735, 16.53061224, 17.14285714, 17.75510204,
       18.36734694, 18.97959184, 19.59183673, 20.20408163, 20.81632653,
       21.42857143, 22.04081633, 22.65306122, 23.26530612, 23.87755102,
       24.48979592, 25.10204082, 25.71428571, 26.32653061, 26.93877551,
       27.55102041, 28.16326531, 28.7755102 , 29.3877551 , 30.        ])

### la forme et le remodelage de tableaux numpy

In [51]:
### nombre d'axes
a =np.array([[1,4,4],[3,5,4]])
print("array",a)
print("dimension",a.ndim)

array [[1 4 4]
 [3 5 4]]
dimension 2


### recuperer ma forme du tableau numpy

In [63]:
### shape montre la forme du tableau
c  =np.array([[1,4,6,5,4],[3,5,4,4,9],[1,4,6,5,4],[3,5,4,4,9],[3,5,4,4,9]])
print("taille c : ", c.shape)
##get recuperer le nombre de ligne et de colonne
#0 pour le ligne
l=c.shape[0]
#1 pour le ligne
c=c.shape[1]
print (f"le nombre de ligne {1} et le nombre de colonne {c} ")

taille c :  (5, 5)
le nombre de ligne 1 et le nombre de colonne 5 


## taille du tableau


In [70]:
t_s =np.array([[1,4,4],[3,5,9],[3,5,9]])
t_s.size
### travailler taille du tableau manuellement
p= t_s.shape[0]*t_s.shape[1]
p

9

In [73]:
### changer la dimension du tableau
d= np.array([1,2,3,4,5,6])
d.reshape(3,2)
d.reshape(3,-1)
d.reshape(-1,3)

array([[1, 2],
       [3, 4],
       [5, 6]])

## aplatir le tableau

In [76]:
## lavel fait la refference mais flat fais la copie
t_flaten = np.ones((2,2))
t_flaten.flatten()

array([1., 1., 1., 1.])

In [77]:
### ravel fait la meme chose que flat
t_ravel =np.ones((2,2))
d= t_ravel.ravel()
d

array([1., 1., 1., 1.])

In [78]:
## modifier la valeur de 1 par copie avec flat
e= t_flaten[1]= 0
e

0

In [79]:
i= t_ravel[1]= 6
i

6

In [80]:
t_ravel

array([[1., 1.],
       [6., 6.]])

In [82]:
t_flaten

array([[1., 1.],
       [0., 0.]])

In [83]:
e= t_flaten[1]
e

array([0., 0.])

In [116]:
t = np.array([[3,4,5],[5,6,7],[8,9,1],[4,2,3]])
t
### afficher la premier colonne du tableau
cl1= np.array([[3],[5],[8],[4]])
cl1

array([[3],
       [5],
       [8],
       [4]])

In [122]:
#####creation de la matrice
t3 = np.array([[0,0,0,0],[0,1,1,0],[0,1,1,0],[0,0,0,0]])
t3

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

In [123]:
### tableau matriciel
t3 = np.array([[1,1,1,1],[1,1,1,1],[1,1,0,0],[1,1,0,0]])
t3

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 0]])

In [126]:
#####creation de la matrice
t3 = np.array([[0,1,1,0],[1,0,0,1],[1,0,0,1],[0,1,1,0]])
t3

array([[0, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 0]])

## les operations arthmetiques

In [128]:
# operation arthmetique Addition, soustraction, multiplication
A = np.array([[1,2],[3,4]])
B = np.eye(2)
somme = A + B
diff = A - B
ele_par_ele = A * B #elles doivent avoir la même taille ! multiplication élément par élément
ele_par_ele_2 = np.multiply(A,B) #elles doivent avoir la même taille ! multiplication élément par é lément
produit = np.dot(A,B) # vrai produit de matrice
print(A)
print(B)
print("somme :", somme)
print("diff :", diff)
print("multiplication élément par élément :", ele_par_ele)
print("multiplication élément par élément 2 :", ele_par_ele_2)
print((ele_par_ele == ele_par_ele_2))
print("produit : ", produit)

[[1 2]
 [3 4]]
[[1. 0.]
 [0. 1.]]
somme : [[2. 2.]
 [3. 5.]]
diff : [[0. 2.]
 [3. 3.]]
multiplication élément par élément : [[1. 0.]
 [0. 4.]]
multiplication élément par élément 2 : [[1. 0.]
 [0. 4.]]
[[ True  True]
 [ True  True]]
produit :  [[1. 2.]
 [3. 4.]]


## calcul de la moyenne

In [130]:
 # syntaxe : array.mean(A, axis)
    ### calcul de la moyenne
A = np.array([[1,2,3],[4,5,6]])
moy = np.mean(A)
moy_ligne = np.mean(A, axis = 1)
moy_col = np.mean(A, 0)
print(A)
print("moyenne tous les élé de A : ", moy)
print("moyenne chaque ligne: ",moy_ligne)
print("moyenne chaque colonne: ",moy_col)

[[1 2 3]
 [4 5 6]]
moyenne tous les élé de A :  3.5
moyenne chaque ligne:  [2. 5.]
moyenne chaque colonne:  [2.5 3.5 4.5]
